### ISSUE TITLE
Error making multidisc PKG game (PS3)

### ISSUE THREAD

**Issue by HiroTex** [sahlberg/pop-fe#11]
I got an error converting the Policenauts game (the English patched version). The PKG file was not created. I tried to make a PKG file with the generated content by pop-fe using another tool, but the 2nd Disc doesn't work.

![image](https://user-images.githubusercontent.com/85416604/162274305-535cf55d-af79-4eff-b8ca-500817946dcd.png)

**Comment by sahlberg** [comment]
Hmm. memory error in pkg.py,   that sounds like there was something wrong with compiling the C module for the crypto during install.
Can you try using the pre-compiled windows version and see if you still get this error?

**Comment by sahlberg** [comment]
But there there still seems to be an issue with multidisc images for PS3.
It is the same code and it is the same EBOOT.PBP that is used on PSP  and on PSP it works fine to switch disks in a multidisc PBP bot on a PS3 it turns out to always be the first disc that is loaded.

I need to look into this more.  And I should not have just assumed that "the EBOOT.PBP worked fine for multidisc on PSP, thus when I load it into a PS3, baked into a PKG, it will work fine too."

**Comment by sahlberg** [comment]
This should be fixed now. I can successfulyl create multidisk
