### ISSUE TITLE
Adiboo & Paziral's Secret (Europe) (En,Fr,De,Es,It) - 8bc2ab966c29c834a82769094c672bc3

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#116]
Adiboo & Paziral's Secret (Europe) (En,Fr,De,Es,It)
8bc2ab966c29c834a82769094c672bc3

**Comment by sahlberg** [comment]
Fixed in https://github.com/sahlberg/pop-fe/actions/runs/8262577457
This one has both pic0 and pic1 links.
Many of the other games (except action replay of course) has assets too, including some have software manuals and snd0 links.
If this is important to you, you might want to re-convert them to get the assets.
