### ISSUE TITLE
Chaos Break doesn't convert properly

### ISSUE THREAD

**Issue by MediaMaquina** [sahlberg/pop-fe#169]
It says converted fine, but the audio track isn't there. It made a 90MB eboot so that shows it has no audio (the audio track alone is 640MB).
btw I want ATRAC3 not CDDA. is it not possible?

```
ID SLES03107
Found an external config for SLES03107
Found cached prebuilt PIC0 https://github.com/sahlberg/pop-fe-assets/raw/master/pic0/728b1dc44ff7e85d238aeeeb824b8cb1
Found cached prebuilt PIC1 https://github.com/sahlberg/pop-fe-assets/raw/master/pic1/824be34ca68665e290a1624b84922b1d
Creating EBOOT
DISC SLES03107
TITLE CHAOS BREAK
Found cached prebuilt SND0 https://github.com/sahlberg/pop-fe-assets/raw/master/snd0/a06a0c4fcac611eead6e56ec5e6338e5
Converting pop-fe-psp-work/TRACK_0_02.wav to pop-fe-psp-work/TRACK_0_02.aea
End of input file.

Creating SND0.AT3
Creating temporary WAV file clamped to 59 second duration pop-fe-psp-work/SND0.WAV
Clamping file to 59000 ms
End of input file.

Create pop-fe-psp-work//SND0.AT3 from pop-fe-psp-work/SND0.EA3
Creating temporary WAV file clamped to 28 second duration pop-fe-psp-work/SND0.WAV
Clamping file to 28000 ms
End of input file.

Create pop-fe-psp-work//SND0.AT3 from pop-fe-psp-work/SND0.EA3
Create PBP file at E:/Desktop/SLES03107/EBOOT.PBP
Inject pop-fe-psp-work/TRACK_0_02.aea at 01d5bda0
```

**Comment by sahlberg** [comment]
It looks like it is there.

"Converting pop-fe-psp-work/TRACK_0_02.wav to pop-fe-psp-work/TRACK_0_02.aea"
This is converting track 2 into atrac3 format.
Atrac3 format is a lossy compressed format, like mp3, and it will be significantly smallr in size than the original uncompressed cdda audio track.

Here is where it injects the atrac3 compressed audio into the eboot:
"Inject pop-fe-psp-work/TRACK_0_02.aea at 01d5bda0"

Looks like it is working. It compressed the audio into ATRAC3 format and injects it into the EBOOT instead of the raw audio tracks.

**Comment by sahlberg** [comment]
Looks like the audio track is converted to ATRAC3 and injected into the EBOOT instead of the CDDA data.
Reuslting in a much smaller EBOOT than if uncompressed CDDA tracks were stored.

Functions as designed.
