### ISSUE TITLE
Option to create lossless PBPs

### ISSUE THREAD

**Issue by rhynec** [sahlberg/pop-fe#18]
Is it possible to create PBPs in such a way that the audio tracks won't be extracted and compressed, and instead the original ISO (bin + cue) can be recovered after conversion? Or is this not currently possible with PBP files?

**Comment by sahlberg** [comment]
Pop-fe used to do this up until recently but I changed it to not write the CD-DA tracks because of requests to allow these PKGs to become much smaller.

I have added a new command line argument to pop-fe :   --whole-disk
Use this to create PKGs where also the raw CD-DA tracks are written to the EBOOT.PBP.
This allows you to extract the full disk image from the EBOOT.PBP and it should be identical to the original .BIN file.

Note, this is an ISO.  ISO can not describe multiple tracks, it is always just the content of the very first data track of a single/multi-track CD-ROM.
To describe multidisc image we use .BIN/.CUE files. The bin file is the raw disc image containing all the tracks, and the .CUE file
describes the individual tracks, where they start, how big they are and what type they are (i.e. data or audio)

If you use --whole-disk   you will now be able to extract the full .BIN file from the EBOOT.PBP. But to use it you will need to create a .CUE file.
You would have to generate a CUE file but that should not be that hard. All the relevant information you need for the CUE file can be found on redump.org for every disk.  You will just massage the data to be in the expected format as in a .CUE file.

**Comment by sahlberg** [comment]
Closing. The feature has been added for this functionality.
