### ISSUE TITLE
PIC0 and PIC1 always the same

### ISSUE THREAD

**Issue by 98DEMAKE** [sahlberg/pop-fe#19]
Using pop-fe-ps3. Worked fine for a couple of times. Now PIC1 is always also PIC0. Checking "Disable PIC0" does nothing either, still uses PIC1 as PIC0.

Does the same both for auto fetched images and custom ones.

**Comment by 98DEMAKE** [comment]
Tried multiple different releases, always the same issue. Everything looks fine in the pop fe UI, but once installed on PS3 the issue comes up.

**Comment by sahlberg** [comment]
What is the display resolution you are running at? Is it 576p ?
Can you try to set it to a higher resolution and disable 576p?

**Comment by 98DEMAKE** [comment]
> What is the display resolution you are running at? Is it 576p ? Can you try to set it to a higher resolution and disable 576p?

Switched from a 576p CRT TV to a 1080p one and the pictures seem to be working now, yes. Unfortunately doesn't fit my usage as is, but it's a great tool regardless.

**Comment by sahlberg** [comment]
Lets re-open it and see if I can do something for 576p.   If not I will close again later.

**Comment by 98DEMAKE** [comment]
Alright, much appreciated. I'll keep an eye out.

**Comment by sahlberg** [comment]
Can you try this, the build is the link at the very bottom called "pop-fe-ui"
https://github.com/sahlberg/pop-fe/actions/runs/3476058985

This is a build artefact of a small chang eI made to try to fix this.  You need to be logged in to GitHub in order to be able to download it. (Github does not allow anonymous access to build artefacts)
So just create an account on github, log in and then download this artefact and test it.

**Comment by 98DEMAKE** [comment]
Works like a charm, thank you very much!

![IMG_20221116_060140](https://user-images.githubusercontent.com/118309446/202080654-86aeb50a-a9bc-44e9-8a8b-953f69ee0566.jpg)

**Comment by sahlberg** [comment]
Thanks for testing and verifying.  I will probably upload this as a new release over the weekend.
The presentation there on your XMB looks very nice.   You are using a custom image for ICON0 and PIC1? (PIC0 looks like it matches a screenshot for that game on www.psxdatacentre.com)  Looks very nice!

Note, IF curate ICON0/PIC0/PIC1 with custom images you can store them next to the bin/cue files and have pop-fe automatically use them instead of downloading random pictures if you need to re-create the PKG in the future and still use the same images.

The filenames to use should match the name of the cue file but instead of ending with .cue  it should end with

_cover.png : for ICON0
_pic0.png : for PIC0
_pic1.png : for PIC1

Example:
Grandia.cue
Grandia.bin
Grandia_cover.png
Grandia_pic0.png
Grandia_pic1.png

**Comment by sahlberg** [comment]
One thing I would like to see now that pop-fe is getting almost feature complete (still some things to implement, like support for manuals in the PS button menu and cdda audio for psp)
would be to have nicely and human curated sets of graohics and audio for the the game.
Maybe a set of themes where each theme has a small ui guidline for what icon0 should look like, and such.

I could easily add a themes selector to pop-fe and the ui and then IF the selected theme has  graphics/audio for the game then it would use it instead of the "radnomly selected from psxdatacentre".
These assets could be stored as data in a github project and be accessed at runtime from pop-fe.

Would you like to start creating such a theme with carefully created assets?  Maybe there are people on psx-place that would like to contribute too? Of course not all games are realistic but if we had themes and the hundred most popular games in a theme that would be much better than the current situation with "better than nothing random images".

What do you think?

The ps1 games are great and they deserve to look great also on the ps3 xmb.

**Comment by 98DEMAKE** [comment]
I'd be down to do that, yeah. I have an easy template, so say the the top hundred for starters shouldn't take too long. You have a discord account?

**Comment by 98DEMAKE** [comment]
Tbh the only thing that bothered me with this tool WAS the fact that the automatic images and audio are kinda all over the place. Stretched, or otherwise just not very appealing. It's cool and easy, but would be way cooler to have a human curated option. 

As you said, all games are obviously not realistic, but I'd assume most people actually play just the top 100 max. And once the top 100 is there, I can do some more obscure games at my own leisure.

Anyway, would be glad to help out. As I've said, it's a great tool. And easiest to use I could find.

**Comment by sahlberg** [comment]
"Tbh the only thing that bothered me with this tool WAS the fact that the automatic images and audio are kinda all over the place. Stretched, or otherwise just not very appealing. "

I agree 100%.  It is better than nothing, so it was a good first step. But a human curated  set would be much superior.
Let me think how it would work and I send a follow up email tomorrow. I have some ideas.
You can email me directly at ronniesahlberg@gmail.com which will be easier to discuss on than this issue-forum-link.

The games are so great. They deserve to be shown at their very best in the XMB too.

**Comment by sahlberg** [comment]
Did you get the emails I sent you?
