### ISSUE TITLE
Cannot override game_id if the input is a multi disc game

### ISSUE THREAD

**Issue by ghost** [sahlberg/pop-fe#27]
> pop-fe# pop-fe.py --psp-dir=/psp --game_id=SLUS01163 /psp/game.cue /psp/game2.cue
> Processing /psp/game.cue ...
> Processing /psp/game2.cue ...
> Try URL http://www.hwc.nat.cu/psx/SLES_028.67_COV.jpg
> Falling back to PSXDATACENTRE for cover
> Id: SLES02867

**Comment by sahlberg** [comment]
Thanks.   I have checked in a fix for this in current master. Please test.

I have also checked in a change so that it will install and build pop-e under linux on all pushes to github and verify that it can create PS3 and PSP images including multidisk.
I will add a test for this too so that it will not have a regression.

**Comment by sahlberg** [comment]
Also, I added a workflow that installs and builds pop-fe on ubuntu and then also runs some tests to create images.
This is based on fake disk images (disk image with an ISO that only contains system.cnf and nothing else).

Might be useful to do something similar to docker. I.e. add a job that set up docker, builds a docker image for pop-fe and tests that it can convert a cue/bin into a PKG.  Do you want to do that?   I don't use docker myself  but I guess I can figure it out if you don't want to.

**Comment by sahlberg** [comment]
Oh, the emulator inspects the disk id and applies patches based on it?

Ok, so currently --game_id only takes a single argument and it only applies to the first disk.
I am happy to change this but I need to understand how/what would work.
I could change it to allow --game_id to take a comma-separated list of IDs instead of just a single one,
i.e.   --game-id=SLUS01623,SLUS01163 

Then it will override the game_id for the first n disks?
Would that work?

(and it really should be --disk_id and not --game_id I think.  I did not know very much about PSX disk games when I started so ...)

**Comment by sahlberg** [comment]
I will do this change to game_id next weekend.

As for editing the EBOOT.PBP. I think that would work for a PSP EBOOT but not a PS3 EBOOT. I think the PS3 only actually reads the disk sectors and the ATRAC3 audio streams from the EBOOT but it reads the PSISOIMG sections from ISO.BIN.DAT, so I think you would need to edit ISO.BIN.DAT but that file is both signed and encrypted so there would be many very annoying manual steps involved to edit it. Probably better to just let pop-fe do it.

You also brought up a good point about libcrypt. I think that should also be changed. I think the libcrypt patching should ignore what --game_id overrides the IDs to be and it should always use the ID that it reads from the bin file itself. That will require some rearrangement of in what order I do things in pop-fe but I can do that change too next weekend.

I.e. so
1, allow --game_id to override the ID for all disks, not just the first one
2, make libcrypt patching ignore --game_id and always use the ID it extracts from the bin file

**Comment by sahlberg** [comment]
Can you try current master?
I changed it so that you can specify a comma separated list of IDs for multidics games. This also applies to if you put a file 'GAME_ID' in the same directory as the cue/bin file.

Libcrypt and generation of subchannel and magic word is still based on the id found in the corresponding cue/bin and is not affected by overriding the is using --game_id.
Similarly, the resolution field (PAL or NTCS) is also based on the id from the cue/bin and is not affected by --game_id.

Is this kind of what you need for overriding the game id?
