### ISSUE TITLE
AttributeError: 'ImageDraw' object has no attribute 'textsize'

### ISSUE THREAD

**Issue by DuckDantas** [sahlberg/pop-fe#33]
![001](https://github.com/sahlberg/pop-fe/assets/141507924/00af631c-c908-4e7c-ad8a-a877548e6540)

**Comment by sahlberg** [comment]
Very strange. The ImageDraw object should definitely have an attribute called textsize. Maybe you have a weird version of PIL installed?

Anyway, there are two ways you can avoid this happening:
1, in pop-fe-psp,  deactivate 'watermark in pic1'.  The textsize is only used when trying to create the watermark (i.e. the game title and game-id)
2, I have added a try/except clause to this function so that IF this happens again it will just skip generating the watermark
instead of failing.

Please try the build artefact in https://github.com/sahlberg/pop-fe/actions/runs/5772951172
It implements the fix to the exception mentioned in 2.
