### ISSUE TITLE
Add support for rom hacks

### ISSUE THREAD

**Issue by deadlyjunk** [sahlberg/pop-fe#40]
Would love to see rom hacks support especially for translation patches of Japan only games

**Comment by sahlberg** [comment]
Do you mean patching the image with a PPF file?
I already PPF files but currently only to handle libcrypt on the targets that does not support the normal ways to deal with libcrypt (i.e. PS2 and PSIO). So I have the code and logic for how to apply a PPF already.

I would need to think a bit on how this could be added to the UI versions (pop-fe-pps3/psp) without cluttering the UI up too much. 

There aren't all that many games with a fans translation anyway so I guess I could add it as a checkbox
that becomes active IF we have a PPF translation for this game, but are greyed out otherwise.

I would need to set up a small database to match the link to the PPF to the disc-id it applies to and the md5sum of the disc image (to prevent the wrong ppf to be applied to the wrong disc) but it is doable.

I would need a lot of help though, to provide a list of links to where pop-fe can download PPFs etc and to test that it all works.  And someone that would keep an eye on the scene and let me know when there are new patches that should be added to pop-fe.

I won't have any time right now, but possibly could do a small test version to see how it would look sometime next week.
Do you have a list of PPF files and the matching disc-ids you can send me?
Something like:

http:/.......   is a zip file that contains a file ABCDE.PPF that is the english fan translation of Aconcagua Disc 1,  original disc checksum that this PPF should apply to is 123abc...

for a handful of games.  Then we can try how it looks and works and we (you) can add more patches to the database?

**Comment by sahlberg** [comment]
Are there other types of hacks you are thinking of aside from translations?

**Comment by sahlberg** [comment]
I have added support for --romhacks to pop-fe.py and tested it with a fan translation of ShinMegamiTensei.
The hacks must either be PPF or XDELTA format.  See the README file for examples on how to use it.
