### ISSUE TITLE
(PSP) Glitchy CDDA audio in some games

### ISSUE THREAD

**Issue by HNKEureka** [sahlberg/pop-fe#62]
I've discovered pop-fe and I've tried a bunch of games with Redbook audio to my PSP. There something wrong and I don't know if the games are the problem or something with the conversion to at3. Pac-Man World (NTSC) title theme starts at the wrong point and the loop offset is kind of broken, and with Rockman X3 (NTSC) the loop offset is broken too at the end of its tracks. I've tried merging the tracks into one .bin before doing the conversion, but it's still the same. I've tested Moto Racer (NTSC) and it's working fine, so I don't know why it's happening.

EDIT: Moto Racer still has issues with some tracks ending abruptly.

**Comment by sahlberg** [comment]
Please try the latest automated build under the ACTIONs tab.
There is a lot of changes right now due to the recently discovered emulator config settings so there is no recent release until things slow down.

This is the latest automated build, please try it : https://github.com/sahlberg/pop-fe/actions/runs/6621882339

Also, there is a thread on gbatemp where people work on creating cnfigs tomimprove games for psp, join it
https://gbatemp.net/threads/new-mode-to-fix-ps1-games-for-psp-and-psvita.607286/

**Comment by HNKEureka** [comment]
Nice. I'll check the thread in case some new stuff appears!

**Comment by sahlberg** [comment]
Ah, so it is fixed in the latest build. I will close this issue then.
If you find games that have issue, that thread is where the people working of tweaking and fixing all games hang out. You can ask directly in the thread about games and they will likely fix them and then give me a config to check into pop-fe.
