### ISSUE TITLE
Config changes revision excerpt after conversion.

### ISSUE THREAD

**Issue by Webardo** [sahlberg/pop-fe#67]
Hello, I noticed an odd thing when checking if the configs were inserted correctly.

This is how the config for Crash Bandicoot 3 looked like before conversion (the config by itself):
![config](https://github.com/sahlberg/pop-fe/assets/76268555/80f347f2-47bc-4bc8-bf6f-c3bd757e4dc7)

And this is how it looks after converting the game:
![eboot](https://github.com/sahlberg/pop-fe/assets/76268555/525aa7ce-c476-400c-8a97-ed21afd66dd2)

Notice how the 60 changes to 70, which may lead to issues on Vita because of the empty config. Having the revision set to 60 works so that the Vita ignores the config, thus it can be seen by PSP only.

**Comment by sahlberg** [comment]
Ah,   
try the latest version that is building now.
On PS3, the config is variable length and thus I strip off the header from the config file and generate a header inside pop-fe. Just so that I can basically concatenate multiple different configs into one if I want to.

When I added config support to psp I did not realize that the config were fixed size so I did the same as in the PS3 case. I.e. strip off the header when reading the config file and generate a header inside pop-fe.
That is wrong to do on PSP since we will never concatenate multiple configs and since they are fixed size.

I changed it now to use the header from inside the config as-is without trying to replace it with one generated inside pop-fe.

**Comment by Webardo** [comment]
Thanks! Just tried the latest version and it works perfectly now.

Indeed configs for POPS are fixed size, just being either 140 bytes when they're for PSP only, and 272 bytes for both PSP and Vita. Interesting to see that the ones for PS3 can vary on size.
