### ISSUE TITLE
Problem with Resident Evil 1.5

### ISSUE THREAD

**Issue by AdrCant** [sahlberg/pop-fe#79]
I had informed you about the existence of the mod for the beta of Resident Evil 1.5 MZD. I'm trying to convert it with the latest version compiled of pop-fe, but it still doesn't recognize the game. I had previously mentioned that this game lacks a proper ID, so the program attempts to find it using the MD5 fingerprint. Here is the log:
cdrom: line in system.cnf does not contain a proper id, read disc label instead
MD5 fingerprint fa456e05ebc9d71cad1d0a0add977315
ID UNKN00000

**Comment by sahlberg** [comment]
That is a different fingerprint to the the one I used/tested. :-(
I have added your fingerprint in https://github.com/sahlberg/pop-fe/actions/runs/7703274294
That should fix the issue and identify your disc correctly.

**Comment by AdrCant** [comment]
"I will try it out and will let you know if the problem is resolved. Additionally, since this mod is still in development, there will be future updates, and the MD5 will change with these. Is there any way for the program to detect and identify the game, regardless of the changes that the MD5 may undergo over time?"

**Comment by sahlberg** [comment]
The most common way to identify the game is by looking in the SYSTEM.CNF file in the iso on track 1.
This file contains a line that looks something like:
  BOOT = cdrom:\SLUS_004.21
to tell the system which file to boot.
In this case the filename SLUS_004.21 refers to the disc-id  SLUS-00421, i.e. Breath Of Fire III.

This is what pop-fe uses by default to indetify the game. Almost all official games use this format and it is the most reliable way to identify a disc.
If the modders could switch to use something similar and pick a unique SLUS identifier then I can add this to pop-fe and then it will detect the game for all future releases going forward.

Internally I used SLUS-99999 for this game. And the md5sum for the disk maps to this game.
If you can ask them to change the name of their executable and update the system.cnf to use something like

BOOT = cdrom:\SLUS_999.99

Then that would make this future proof.
(I picked SLUS-99999 because sony never used this number for any official release)


Similalrly we can do teh same thing for other homebrew and fan made games to have them be auto-detected too.
