### ISSUE TITLE
Request: Add option to disable PIC1 and replace with game title text (PSP)

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#81]
For PSP conversions, I'd like to be able to disable both PIC0 and PIC1, and show just the ICON0 pic and the game title text against the PSP background, as can be done in PSX2PSP. Please see the attached pic.

Also, the 'Watermark in PIC1' option doesn't seem to do anything, as far as I can tell.

![PSP](https://github.com/sahlberg/pop-fe/assets/158531648/29facc2f-b60c-452e-8d97-677fa6a4422f)

**Comment by sahlberg** [comment]
I have implemented the first part here:
https://github.com/sahlberg/pop-fe/actions/runs/7752717977

It adds a disable pic1 button. I haven't tested it fully since I nowadays mostly/only play on ps3, not psp but let me know how it works.

Watermark in pic1 is supposed to add a tiny line of text in the lower right corner to show the disc-id, like 'slus-12345'
and add a tiny string of text in the upper right, justbelow the battery indicator symbol to show the name.
This only happens on pic1. It is supposed to work but might have broken/regressed as I dont play on psp regularely.

**Comment by bombjack84** [comment]
Thanks, this now works and I get the same result as the example pic I posted. I guess the PSP automatically adds the title if PIC1 is missing?

There are a couple of small issues though:

1. The 'Disable PIC1' button doesn't seem to do anything, and the 'Disable PIC0' button now seems to toggle both PIC0 and PIC1 in turn.

2. The choices aren't saved when a new disc is loaded, the 'Disable PIC0/PIC1' buttons have to be switched off and on again.

**Comment by sahlberg** [comment]
Yeah it was a bit broken.   I have pushed a fix that should resolve it:
https://github.com/sahlberg/pop-fe/actions/runs/7985884513
