### ISSUE TITLE
(PSP) Failed to read game id. Falling back to raw read - ID UNKN00000 Exception

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#91]
It seems quite a few games can't have their ID read, which causes an exception in pop-fe:

MD5 fingerprint 8bc2ab966c29c834a82769094c672bc3
Failed to read game id. Falling back to raw read
ID UNKN00000
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 378, in on_path_changed
  File "pop-fe-psp.py", line 269, in update_assets
  File "pop-fe-psp.py", line 425, in update_preview
AttributeError: 'NoneType' object has no attribute 'mode'

Perhaps this exception could be caught, then the user could manually enter the Game ID and Title into the GUI?

I've only tested A-C so far, I've found these games to be affected:

Adiboo & Paziral's Secret (Europe) (En,Fr,De,Es,It)
Air Hockey (USA)
All Star Racing 2 (USA)
All Star Watersports (Europe)
Animal Snap - Rescue Them 2 by 2 (Europe)
Bratz - Dress Up, Get Down and Be a Bratz Superstar! (USA) (En,Fr,Es)
Cabela's Ultimate Deer Hunt - Open Season (USA)
California Surfing (Europe)
Cindy's Caribbean Holiday (Europe)
Cindy's Fashion World (Europe)
Cleopatra's Fortune (USA)
Cosmic Race (Japan)
Crime Crackers (Japan)
CT Special Forces - Back to Hell (Europe) (En,Fr,De,Es,It,Nl)
CT Special Forces 3 - Bioterror (Europe) (En,Fr,De,Es,It,Nl)
Cyberwar (Japan)

**Comment by sahlberg** [comment]
I think I have fixed the exception in the latest commit that is building right now so there should not be an exception on line 425 any more.
https://github.com/sahlberg/pop-fe/actions/runs/8035265714

At some stage maybe we should add a way for the user to manually specify the game-id in the GUI but it is probably too early.
If there are games that are not recognized I would prefer them to be opened as bugs so that I can fix the autodetection.
At least for now.

Any games that fail to autodetect, please open a bug for the game and paste the md5sum that is printed.
Then I can add a manual override for that particular disk to the correct game entry.

**Comment by bombjack84** [comment]
Using that latest commit, an exception occurs just a few lines later:

MD5 fingerprint 8bc2ab966c29c834a82769094c672bc3
Failed to read game id. Falling back to raw read
ID UNKN00000
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 378, in on_path_changed
  File "pop-fe-psp.py", line 269, in update_assets
  File "pop-fe-psp.py", line 433, in update_preview
AttributeError: 'NoneType' object has no attribute 'resize'

If these exceptions could be bypassed, then couldn't the user already change the game ID and title (from UNKN00000 and UNKNOWN respectively) in the GUI before pressing the Create EBOOT button? This can be done in PSX2PSP.

I admire you wanting to fix each of these independently, but I'd estimate there's probably hundreds of unrecognised discs. I only tested around 30% of A-C titles and already found 16 instances. It'd be better to give the user the option to fix the problem themselves in the GUI than have to wait for a fix. Maybe you could automatically report these issues back to yourself to fix later?

**Comment by bombjack84** [comment]
I have some spare time to start converting the Redump set, so I'm happy to test and list any issues, including listing the 'unknown ID' discs.

However it would be really helpful if you could fix the exceptions so that the app doesnt crash when finding an unknown disc. This would speed up my testing greatly by not having to restart the app and change the settings each time (output directory etc.).

**Comment by sahlberg** [comment]
That sounds like a compromise that can work.
I fixed another place where it crashes on an unknown game, so please try this:
https://github.com/sahlberg/pop-fe/actions/runs/8259640529
It should flag these games as UNKNOWN and just not create any assets for icon0/pic0/pic1

As a temporary workaround, you can place a file 'GAME_ID' in the same direcotry as the CUE file and it will override the
check by scanning the disc.
The format is 9 characters, upper case, example 'SLUS12345'

Please open a bug for each game that fails for I can fix it in the database.

**Comment by sahlberg** [comment]
Ah, this crash is if we have disabled pic1   but the database did not have a pic1.

In this case, when pic1 is disabled we should just create a blank dummy background and force it to mode 'rgba' instead of trying to use the mode for pic1 which may or may not exist.

It is updated in the latest build
